### ISSUE TITLE
Recording causing immense web UI sluggish behavior into timeout

### ISSUE THREAD

**Issue by akumar95** [MrBrax/LiveStreamDVR#327]
Hello,

So I have this problem that when a stream is recorded, instantly the web UI hangs and ultimately leading to error 523 timeouts. The docker compose file I'm running is:

```
version: "3.8"
services:
  web:
    build: .
    image: mrbrax/twitchautomator:master
    ports:
      - "8082:8080"
    volumes:
      - /volume1/Data/twitchauto:/usr/local/share/twitchautomator/data
    environment:
      - NODE_ENV=production
```
The VPS LivestreamDVR has said specs:
```
AMD EPYC 7J13 CPU
96GB RAM
Ubuntu 22.04
```

The hard drive space on this VPS isn't as much as I'd like so I have my Synology mounted to the VPS so I have 14TB of space to use. I've tried mounting it via NFS and SMB but the webpage still hangs unless I restart the container. Looking at the logs the application has no issues continuing the recording but the page is where the problem persists. 

Would the issue be caused by my Synology or somewhere in my network?
